In [1]:
import pandas as pd
test = pd.read_csv("test.csv")
test.head()

   Index  Height(Inches)  Weight(Pounds)
0   6869        68.42447        134.2855
1  24017        67.89663        111.9666
2   9669        67.65922        135.9871
3  13641        69.01299        126.3802
4  14019        69.01055        100.1810

In [2]:
train = pd.read_csv("train.csv")
train.head()

   Index  Height(Inches)  Weight(Pounds)
0  23312        67.94897        110.6746
1  23624        66.55460        127.0069
2   1021        70.05212        140.2298
3  12646        68.48066        133.0611
4   1534        66.11208        115.4493